export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_COURSES_FAILED = "LOAD_COURSES_FAILED";

export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAILED = "CREATE_COURSE_FAILED";

export const EDIT_COURSE_SUCCESS = "EDIT_COURSE_SUCCESS";
export const EDIT_COURSE_FAILED = "EDIT_COURSE_FAILED";

export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILED = "DELETE_COURSE_FAILED";

export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const LOAD_AUTHORS_FAILED = "LOAD_AUTHORS_FAILED";
